AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "AWS Lambda function for converting Telegram channel posts to JSON feed."

Resources:
  TgChannelToRssFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Timeout: 300
      MemorySize: 128
      CodeUri: .
      Handler: tg-channel-to-rss
      Events:
        FeedLanding:
          Type: Api
          Properties:
            Path: /feed
            Method: get
        GetChannelAsRss:
          Type: Api
          Properties:
            Path: /feed/{channel_name}
            Method: get
  LambdaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${TgChannelToRssFunction}"
      RetentionInDays: 14

Outputs:
  TgChannelToRssApi:
    Description: "API Gateway endpoint URL for TgChannelToRss function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/feed/"
